### ISSUE TITLE
Api de Evento faltando propriedades

### ISSUE THREAD

**Issue by tjambeiro** [gesuvs/bora-node#1]
**Campos Criados**
name
owner
startDay
startEnd
roles
password
isPublic

**Campos Faltantes**
CEP
Numero rua
Valor
Evento Gratuito
Categorias
Quantidade de pessoas

Segue abaixo uma print da tela com os campos

![Screenshot from 2020-06-04 22-16-39](https://user-images.githubusercontent.com/42386582/83826931-8c371b80-a6b3-11ea-8587-6476122ee635.png)

**Comment by gesuvs** [comment]
![Screenshot_20200615_160821](https://user-images.githubusercontent.com/42353858/84696173-7383fc80-af22-11ea-857c-753cae9d3a58.png)

CEP -> OK
Numero rua -> OK 
Valor - -> OK
Evento Gratuito -> OK
Categorias -> OK
Quantidade de pessoas -> essa informação sera consultada na tabela que salva os participantes de cada evento.
